BEGIN;
DROP TABLE userRoles;
DROP TABLE users;
DROP TABLE userkeys;
DROP TABLE organizations;
DROP TABLE invites;
DROP TABLE teams;
DROP TABLE teamusers;
DROP TABLE domains;
DROP TABLE shortlinks;
DROP TABLE unusedshortlinks;
DROP TABLE accesslogs;
DROP TABLE tags;
DROP TABLE shortlinktags;
DROP TABLE payplans;
DROP TABLE organizationpayplans;
DROP TABLE payschedules;
DROP TABLE revenues;
COMMIT;