BEGIN;
CREATE TABLE IF NOT EXISTS users(
   Id INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
   Name VARCHAR(255) NOT NULL,
   Email VARCHAR(50) NOT NULL,
   CreatedOn DATETIME NOT NULL,
   ModifiedOn DATETIME NOT NULL,
   LastLogin DATETIME NOT NULL
);


CREATE TABLE IF NOT EXISTS urls(
   Hash VARCHAR(16) PRIMARY KEY NOT NULL,
   OriginalUrl VARCHAR(255) NOT NULL,
   CreatedOn DATETIME NOT NULL,
   ModifiedOn DATETIME NOT NULL,
   ExpirationDate DATETIME NOT NULL,
   UserId INT NOT NULL
);


CREATE INDEX idx_userId ON Urls (UserId);
COMMIT;