BEGIN;
CREATE TABLE IF NOT EXISTS users(
   Id CHAR(36) NOT NULL PRIMARY KEY,
   Name VARCHAR(255) NOT NULL,
   Email VARCHAR(50) NOT NULL,
   CreatedOn DATETIME NOT NULL,
   ModifiedOn DATETIME NOT NULL,
   LastLogin DATETIME NOT NULL
);
CREATE UNIQUE INDEX idx_email
on users (Email);


CREATE TABLE IF NOT EXISTS urls(
   Hash VARCHAR(16) PRIMARY KEY NOT NULL,
   OriginalUrl VARCHAR(255) NOT NULL,
   CreatedOn DATETIME NOT NULL,
   ModifiedOn DATETIME NOT NULL,
   ExpirationDate DATETIME NOT NULL,
   IsDeprecated BOOLEAN NOT NULL,
   UserId CHAR(36) NOT NULL
);
CREATE UNIQUE INDEX idx_original_url ON urls (OriginalUrl);
CREATE INDEX idx_userId ON Urls (UserId);


CREATE TABLE IF NOT EXISTS userkeys(
   Id CHAR(36)  NOT NULL PRIMARY KEY,
   ApiKey VARCHAR(255) NOT NULL,
   CreatedOn DATETIME NOT NULL,
   ModifiedOn DATETIME NOT NULL,
   ExpirationDate DATETIME NOT NULL,
   UserId CHAR(36) NOT NULL,
   IsActive BOOLEAN NOT NULL
);

COMMIT;